
author:
    - name: Paris Davis
      email: parisnd125@gmail.com

date: 4/16/2025

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
